import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { Global } from '@emotion/react'
import { GlobalStyle } from '../styles/GlobalStyle'
import { css } from '@emotion/react'
import Head from 'next/head'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Global styles={GlobalStyle} />
      <Component {...pageProps} />
    </>
  )
}
